### ISSUE TITLE
Error mysql

### ISSUE THREAD

**Issue by SMarc1** [Artillex-Studios/AxInventoryRestore#1]
Error: https://pastebin.com/Vd0s87zG

Pufferfish 1.20.1

**Comment by SMarc1** [comment]
yes

**Comment by BenceX100** [comment]
Okay, I will test this soon

**Comment by BenceX100** [comment]
I found the issue, also I will make the data migration mentioned in the last update and upload the fixed jar in like 30 minutes, thanks for reporting

**Comment by BenceX100** [comment]
Please check if https://github.com/Artillex-Studios/AxInventoryRestore/releases/tag/1.2.1 fixed the issue
