### ISSUE TITLE
Please update it to 1.20.6.

### ISSUE THREAD

**Issue by lukehemmin** [Artillex-Studios/AxInventoryRestore#12]
Please update it to 1.20.6.
Items are evaporating after I put it in because I thought it was running on 1.20.6.
Also, an error occurs when entering the command.

**Comment by BenceX100** [comment]
We are waiting for a gui library (triumph-gui) to update to 1.20.6.

**Comment by lukehemmin** [comment]
Is it possible to update to 1.20.6 now?
@BenceX100
