### ISSUE TITLE
error when server closes

### ISSUE THREAD

**Issue by Z3r0xh** [Artillex-Studios/AxInventoryRestore#17]
This error happens when connected to mysql and the server closes, build [[0d6766e]

https://mclo.gs/wF8pK2c

**Comment by AverageGithub** [comment]
This was most likely fixed in the last version, could you try running that?

**Comment by Z3r0xh** [comment]
> This was most likely fixed in the last version, could you try running that?

It seems to be working fine now.

Thank you so much!
