### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by dinobossytnew** [Artillex-Studios/AxInventoryRestore#20]
It seems that MySQL is well connected, but the data is not being saved. It seems like it’s not working. I recommend that you test this function with 10-5 users and force inventory saves as well.

**Comment by AverageGithub** [comment]
Hi, could you check with the new version?

**Comment by AverageGithub** [comment]
This was most likely fixed in the last version, could you try running that?

**Comment by dinobossytnew** [comment]
fixed
