### ISSUE TITLE
Error mysql 

### ISSUE THREAD

**Issue by SMarc1** [Artillex-Studios/AxInventoryRestore#4]
https://pastebin.cayeoficial.com/upepenawed.md

**Comment by SMarc1** [comment]
ver 1.2.2

**Comment by SMarc1** [comment]
in version 1.2.3 same error

**Comment by BenceX100** [comment]
This probably happens because you use axir on multiple servers, right? And a player haven't joined one of them and the server can't find them. I will publish a fix for this in a few minutes

**Comment by SMarc1** [comment]
If I use axir on 8 synchronized servers xD

**Comment by BenceX100** [comment]
Should be fixed in https://github.com/Artillex-Studios/AxInventoryRestore/releases/tag/1.3.0

**Comment by SMarc1** [comment]
I will try it

**Comment by SMarc1** [comment]
Works perfectly
