### ISSUE TITLE
bugs the plugin data items

### ISSUE THREAD

**Issue by dinobossytnew** [Artillex-Studios/AxInventoryRestore#7]
Data that is not saved list by dinobossyt test 7w7:

Armors/Items from ItemsAdder do not preserve their NBT, and therefore, they lose their model or texture.
Premium executableitems' Armors/Items do not preserve their NBT data, meaning the activators, and they lose them, so it is not possible to save them correctly.
Armors/Items from AdvancedItems are not saved correctly and lose effects.
Armors/Items from mmoitems are saved, but sometimes they lose NBT data and 3D models.
The data from advancedenchantment and forgeenchantment is not saved correctly when I try to pick up an item from the menu, as it loses the effects.
Mythicmobs items' data is lost, meaning effects.

Clarifications for the data:
It was tested on 1.18.x and 1.20.x; this was on an individual server where I tested each plugin separately.
It is clarified that Paper Spigot and Spigot were used to conduct the tests and compare performance.
It is clarified that the plugin was tested with 10 users plus staff around me.
It is clarified that lores and custom names are saved; that is good, at least.
It is clarified that only effects and activators, targets, are lost.
It is clarified that apparently, sometimes the item saving is not accurate, and therefore, some are not saved correctly.
No errors were detected in the console during and after the tests.
It is clarified that premium content was used, and I am a buyer of these plugins, so I did not use anything from another website other than Spigot, Polymart, MCMarket.

**Comment by BenceX100** [comment]
Hello, I can not recreate this issue, all the NBT should be saved, can you provide a video showing the whole process? And also the output of /ver possibly

**Comment by dinobossytnew** [comment]
ok wait plise
